# Generated by Django 4.0.3 on 2022-05-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_advertisement_fromcomp_product_setting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
