# Generated by Django 4.0.3 on 2022-06-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_rename_comments_commentsp_commentsb'),
    ]

    operations = [
        migrations.AddField(
            model_name='useron',
            name='password',
            field=models.CharField(default='Asbezaye', max_length=100),
        ),
    ]
